name: 'Manage README'
description: 'A GitHub Action to manage README files.'
author: 'caiton1'
inputs:
  action:
    description: 'Action to perform on README.'
    required: true
  user:
    description: 'The requesting user'
    required: true
  content:
    description: 'Content to update or create README.'
    required: false
  replace_pattern:
    description: 'Pattern to replace in README.'
    required: false
runs:
  using: 'node20'
  main: 'index.js'